{"name": "test_create_two_couriers_with_same_login", "status": "passed", "description": "Тест на получение кода ошибки 409, при создании курьера с существующим \"login\"", "start": 1723299381227, "stop": 1723299381822, "uuid": "8464cddf-5b83-431f-a961-209f9d87979f", "historyId": "9f70c8cb1f41e8cb137f6ca317155213", "testCaseId": "9f70c8cb1f41e8cb137f6ca317155213", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_two_couriers_with_same_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "LAPTOP-NLGTCNSI"}, {"name": "thread", "value": "20544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}